### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kabluinc** [Awzaw/AnvilConverter#1]
The converter isn't working for me. Shows this error:

`C:\Users\Gamer27832 server\Desktop\AnvilConverter-master>java -jar AnvilConverter.jar Prison
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at net.minecraft.world.level.storage.AnvilConverter.main(AnvilConverter.java:35)

C:\Users\Gamer27832 server\Desktop\AnvilConverter-master>PAUSE
Press any key to continue . . .`

My start.bat is:

`java -jar AnvilConverter.jar world
PAUSE`

**Comment by Awzaw** [comment]
```java -jar "/PathTo/AnvilConverter.jar" /PathTo/PocketMine/worlds worldtoconvert pmanvil```

Updated*

**Comment by Awzaw** [comment]
```java -jar AnvilConverter.jar /PATHTOPOCKETMINE/worlds PAUSE pmanvil```

**Comment by kabluinc** [comment]
The command line console just instantly closes. Iv tried putting the mcr world in the same world as the converter folder and made it java -jar AnvilConverter.jar World PAUSE pmanvil but still it instant closes. 

When I open a command line console in the converter folder, it says World called PAUSE is not convertible to the Anvil format

'Map converter for Minecraft, from format "McRegion" to "Anvil". (c) Mojang AB 2012

Usage:
        java -jar AnvilConverter.jar <base folder> <world name>
Where:
        <base folder>   The full path to the folder containing Minecraft world folders
        <world name>    The folder name of the Minecraft world to be converted
Example:
        java -jar AnvilConverter.jar /home/jeb_/minecraft world'

**Comment by kabluinc** [comment]
Many thanks!
