### ISSUE TITLE
Some Blocks with Extended IDs are being Randomly Replaced

### ISSUE THREAD

**Issue by markkrueg** [Awzaw/AnvilConverter#4]
Here is an odd "block replacement" we have found. Player quote:

> Some blocks are being replaced by other blocks in a strange mathematical pattern. I've only observed this with clay, wool, and slabs so it probably only happens to blocks with extended IDs (ie 35:1 vs 35).

![Image of Replaced Blocks](http://i.imgur.com/qNuNye0.jpg)

Here is an identical picture on the original mcregion world:

![Image of Correct Original](https://i.imgur.com/vwcP4XT.jpg)

**Comment by markkrueg** [comment]
I have isolated this specific .mcr file and done a conversion with this file and one other; and the results are repeatable. No errors are produced by AnvilConverter.jar during conversion.

So I will be able to test this issue quickly when we come up with a potential solution.

**Comment by markkrueg** [comment]
As requested, here is an example world to use for testing.

[swapped_wood_world.zip](https://github.com/Awzaw/AnvilConverter/files/894439/swapped_wood_world.zip)

**Comment by Awzaw** [comment]
Fixed, sorry it took so long!
